# Generated by Django 3.2 on 2022-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dr_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('hospital_name', models.CharField(default='', max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('category', models.CharField(default='', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mr_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('mr_username', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('ppt_path', models.CharField(max_length=255)),
            ],
        ),
    ]
