# Generated by Django 3.2 on 2022-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('mr_username', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timestamp', models.DateTimeField()),
                ('ppt_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='visits',
        ),
        migrations.AddField(
            model_name='dr_user',
            name='mr_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
