# Generated by Django 4.0.3 on 2022-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mr_user',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=50),
        ),
    ]
