# Generated by Django 4.0.3 on 2022-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_pic',
            field=models.ImageField(blank=True, null=True, upload_to='slides'),
        ),
    ]
