# Generated by Django 4.0.3 on 2022-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_slide_slide_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
