# Generated by Django 4.0.6 on 2022-07-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_mr_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('ppt_slides', models.CharField(max_length=255)),
            ],
        ),
    ]
